# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dication.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dicationDialog(object):
    def setupUi(self, dicationDialog):
        dicationDialog.setObjectName("dicationDialog")
        dicationDialog.resize(841, 661)
        self.verticalLayout = QtWidgets.QVBoxLayout(dicationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_player = QtWidgets.QGroupBox(dicationDialog)
        self.groupBox_player.setMaximumSize(QtCore.QSize(16777215, 175))
        self.groupBox_player.setObjectName("groupBox_player")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_player)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_audioFileSelect = QtWidgets.QFrame(self.groupBox_player)
        self.frame_audioFileSelect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_audioFileSelect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_audioFileSelect.setObjectName("frame_audioFileSelect")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_audioFileSelect)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_audioFileSelect)
        self.label_2.setMinimumSize(QtCore.QSize(88, 26))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_audioPath = QtWidgets.QLineEdit(self.frame_audioFileSelect)
        self.lineEdit_audioPath.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_audioPath.setObjectName("lineEdit_audioPath")
        self.horizontalLayout_2.addWidget(self.lineEdit_audioPath)
        self.pushButton_openAudio = QtWidgets.QPushButton(self.frame_audioFileSelect)
        self.pushButton_openAudio.setObjectName("pushButton_openAudio")
        self.horizontalLayout_2.addWidget(self.pushButton_openAudio)
        self.verticalLayout_3.addWidget(self.frame_audioFileSelect)
        self.frame_wordListFileSelect = QtWidgets.QFrame(self.groupBox_player)
        self.frame_wordListFileSelect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_wordListFileSelect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_wordListFileSelect.setObjectName("frame_wordListFileSelect")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_wordListFileSelect)
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_wordListFileSelect)
        self.label.setMinimumSize(QtCore.QSize(88, 26))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_wordListPath = QtWidgets.QLineEdit(self.frame_wordListFileSelect)
        self.lineEdit_wordListPath.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_wordListPath.setObjectName("lineEdit_wordListPath")
        self.horizontalLayout_3.addWidget(self.lineEdit_wordListPath)
        self.pushButton_openWordList = QtWidgets.QPushButton(self.frame_wordListFileSelect)
        self.pushButton_openWordList.setObjectName("pushButton_openWordList")
        self.horizontalLayout_3.addWidget(self.pushButton_openWordList)
        self.verticalLayout_3.addWidget(self.frame_wordListFileSelect)
        self.frame_playControl = QtWidgets.QFrame(self.groupBox_player)
        self.frame_playControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_playControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_playControl.setObjectName("frame_playControl")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_playControl)
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sliderPosition = QtWidgets.QSlider(self.frame_playControl)
        self.sliderPosition.setOrientation(QtCore.Qt.Horizontal)
        self.sliderPosition.setObjectName("sliderPosition")
        self.horizontalLayout.addWidget(self.sliderPosition)
        self.label_playProgress = QtWidgets.QLabel(self.frame_playControl)
        self.label_playProgress.setObjectName("label_playProgress")
        self.horizontalLayout.addWidget(self.label_playProgress)
        self.pushButton_play = QtWidgets.QPushButton(self.frame_playControl)
        self.pushButton_play.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_play.setObjectName("pushButton_play")
        self.horizontalLayout.addWidget(self.pushButton_play)
        self.verticalLayout_3.addWidget(self.frame_playControl)
        self.verticalLayout.addWidget(self.groupBox_player)
        self.groupBox_dication = QtWidgets.QGroupBox(dicationDialog)
        self.groupBox_dication.setObjectName("groupBox_dication")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_dication)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_wordInput = QtWidgets.QLineEdit(self.groupBox_dication)
        self.lineEdit_wordInput.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_wordInput.setObjectName("lineEdit_wordInput")
        self.verticalLayout_2.addWidget(self.lineEdit_wordInput)
        self.label_wordStatus = QtWidgets.QLabel(self.groupBox_dication)
        self.label_wordStatus.setEnabled(True)
        self.label_wordStatus.setObjectName("label_wordStatus")
        self.verticalLayout_2.addWidget(self.label_wordStatus)
        self.verticalLayout.addWidget(self.groupBox_dication)
        self.pushButton_next = QtWidgets.QPushButton(dicationDialog)
        self.pushButton_next.setObjectName("pushButton_next")
        self.verticalLayout.addWidget(self.pushButton_next)

        self.retranslateUi(dicationDialog)
        self.pushButton_openAudio.clicked.connect(dicationDialog.btn_open_audio_clicked) # type: ignore
        self.pushButton_play.clicked.connect(dicationDialog.btn_play_clicked) # type: ignore
        self.pushButton_openWordList.clicked.connect(dicationDialog.btn_open_word_list_clicked) # type: ignore
        self.pushButton_next.clicked.connect(dicationDialog.btn_next_clicked) # type: ignore
        self.lineEdit_wordInput.returnPressed.connect(dicationDialog.line_word_input_return_pressed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dicationDialog)

    def retranslateUi(self, dicationDialog):
        _translate = QtCore.QCoreApplication.translate
        dicationDialog.setWindowTitle(_translate("dicationDialog", "Dication"))
        self.groupBox_player.setTitle(_translate("dicationDialog", "Player"))
        self.label_2.setText(_translate("dicationDialog", "Audio:"))
        self.pushButton_openAudio.setText(_translate("dicationDialog", "Open"))
        self.label.setText(_translate("dicationDialog", "World List:"))
        self.pushButton_openWordList.setText(_translate("dicationDialog", "Open"))
        self.label_playProgress.setText(_translate("dicationDialog", "time"))
        self.pushButton_play.setText(_translate("dicationDialog", "Play"))
        self.groupBox_dication.setTitle(_translate("dicationDialog", "Dication"))
        self.lineEdit_wordInput.setPlaceholderText(_translate("dicationDialog", "input the word"))
        self.label_wordStatus.setText(_translate("dicationDialog", "x: listining fail"))
        self.pushButton_next.setText(_translate("dicationDialog", "Next"))
        self.pushButton_next.setShortcut(_translate("dicationDialog", "Return"))
